### ISSUE TITLE
Stack widget with 'overflow' property with latest flutter version (1.22)

### ISSUE THREAD

**Issue by romanlytvyn** [imtoori/flutter-slide-to-act#1]
Looks like the recent flutter version broke the library:

```
/c:/Runtime/flutter/.pub-cache/hosted/pub.dartlang.org/slide_to_act-0.1.3/lib/slide_to_act.dart:126:25: Error: No named parameter with the name 'overflow'.
                        overflow: Overflow.clip,
                        ^^^^^^^^
/c:/Runtime/flutter/packages/flutter/lib/src/widgets/basic.dart:3273:3: Context: Found this candidate, but the arguments don't match.
  Stack({
  ^^^^^
```

**Comment by romanlytvyn** [comment]
Anyone is welcome to use a forked version until #2 is merged:
```
  slide_to_act:
    git:
      url: git://github.com/romanlytvyn/flutter-slide-to-act.git
      ref: fix-recent-flutter-compatibility-issue
```
